name: ✨ Request a feature
description: Richiedi una nuova feature
title: "[FR] (feature summary)"
labels: 'T: Feature Request'
body:
  - type: markdown
    attributes:
      value: >
        Vuoi farci delle domande? Iscriviti al [nostro gruppo facebook](https://www.facebook.com/groups/flyingbearghost) e chiedi tutto quello che ti interessa.

  - type: markdown
    attributes:
      value: >
        **Grazie per la tua richiesta!**

        ## Prima di effettuare una richiesta.

        - leggi e cerca di capire come funziona il firmware. Se ci fossero cosa non chiare, contattaci [sul nostro gruppo facebook](https://www.facebook.com/groups/flyingbearghost) e ti risponderemo.

        - Verifica che la tua richiesta non sia già presente nell'ultima versione in Master.


  - type: textarea
    attributes:
      label: "La tua richiesta è collegata a un problema o ad una tua esigenza? Descrivila."
      description: "Una chiara descrizione del tuo problema: (ad esempio: Mi servirebbe X, ma posso fare solo Y)."

  - type: textarea
    attributes:
      label: "Hai bisogno di supporto nell'installare il firmware?"
      description: "Dicci quale sia la tua scheda madre, la stampante e le tue esigenze e proveremo darti aiuto, altrimenti scrivi nel nostro gruppo Facebook."

  - type: textarea
    attributes:
      label: Descrivi la tua richiesta
      description: Una descrizione chiara della feature che vorresti e il comportamento che vorresti.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Informazioni aggiuntive
      description: Aggiungi qualsiasi informazione aggiuntiva, foto o screenshot che potrebbe aiutarci a sviluppare al meglio la tua richiesta.
